### ISSUE TITLE
169677 - [Newsroom] [High]Sitemap- Changes in sitemap are not reflected in internal search in en and non-en geo

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#306]
**Severity 2 - High**

**Steps to Reproduce:** 
1. Open URL https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
2. Click on sidekick
3. Add the word document under sharepoint
4. Documents > sites > Accenture > newsroom > en > news > 2023
5. Sampla page- [Rashi Test Page.docx](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/Shared%20Documents/sites/accenture/newsroom/en/news/2023/Rashi%20Test%20Page.docx?d=wef9b6e14f7874303b2e770046f15642e&csf=1&web=1&e=ikxd4c)
6. Publish the doc
7. Verify the added document in sitemap
https://tempnewsroom.accenture.com/sitemap.xml
8. Verify the added document in search page
https://main--accenture-newsroom--hlxsites.hlx.page/search
Actual: Document is visible under sitempa but 0 result in the search.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/ff14a4fb-565f-4584-a8ca-0820a343bb33)

![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/269b5f57-94c7-4ff2-9a49-6b2939d531a9)

Expected: Added document in sitemap should be searched.

Note- Issue exists in non-en geo

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/169677
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
**Investigation notes:**

1. If you look at what is in query-index the title you have in the doc is not visible there. In query index this is the title "Accenture and Adobe Unlock Content Supply Chain Value to Help Enterprise Brands Cut Costs, Increase Efficiencies and Drive Growth"

2. If you look at the preview link - it shows that you have made changes to the doc that have not been published - the red dot on the Publish button 
![Screenshot 2023-10-11 at 12 48 54 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/824ab3b5-af64-49ee-a5ae-da0ad0b4b9f9)

I've gone ahead and published it for your test and now it shows up as "Test-Accenture and Adobe Unlock..." correctly in query-index Excel.

However it is not showing up with the updated title and description in the json just yet. https://main--accenture-newsroom--hlxsites.hlx.page/query-index.json?sheet=articles

This could be because it did not get published for some reason after indexing.

Manually published the query-index and now i see the Test-Accenture in the title in the query-index.json

However, when I search for "https://main--accenture-newsroom--hlxsites.hlx.live/search?q=Test-Accenture" I still don't see the new article show up.

@ravkiran what do you think could be the problem here?

**Comment by ravkiran** [comment]
looks like this url https://main--accenture-newsroom--hlxsites.hlx.live/query-index.json?offset=0&limit=255&sheet=articles is cached and we're not able to clear that cache, looking for options to clear the cache.

**Comment by ravkiran** [comment]
after reindexing, the issue is fixed
<img width="1417" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/2a226212-ab18-4bc8-9ec3-ed7859d54e61">

**Comment by veejayricana** [comment]
Hi @ravkiran, what are step in triggering reindex to fix this issue?
