### ISSUE TITLE
PNF link for cloudfront

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#331]
Description of the issue:  Upon accessing the URL of CloudFront for this page: 
Page is not found.

Steps to replicate:
1. Access the url:  
- https://tempnewsroom.accenture.com/news/accenture-and-blue-yonder-help-companies-accelerate-supply-chain-transformation--in-the-cloud.htm
- https://tempnewsroom.accenture.com/industries/consumer-goods--services **<In all geo>**

**Word Document:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/950a3364-0b00-4920-b0a5-57792b5e24d6)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/ef3a29d5-6092-4e3a-af6d-a385ebee74b3)
And Also upon checking, if I replace the double dash to single dash the page will not be PNF. If I do that the file name and link will not be the same. 

**Expected:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/578db12c-8dce-47ca-b332-959f12128eec)
Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/14abecc2-3d14-42e4-afec-0702d32ba58b)

Azdo Link : https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/290108

cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Updated the redirects in EN to replace -- with - in all the target cells. Should be good to go now and this will redirect properly now.

**Comment by veejayricana** [comment]
Hi @amol-anand the page is still redirecting to single dash not in double dash. 
- https://tempnewsroom.accenture.com/news/2020/accenture-and-blue-yonder-help-companies-accelerate-supply-chain-transformation--in-the-cloud
- https://tempnewsroom.accenture.com/industries/consumer-goods--services

**Comment by amol-anand** [comment]
yes, because the original link is accenture-and-blue-yonder-help-companies-accelerate-supply-chain-transformation--in-the-cloud.htm (with the extension) that's why it's not redirecting for you. add the .htm and it will work. We only care about redirecting the existing site links (which all have .htm)

Test this: 

https://main--accenture-newsroom--hlxsites.hlx.live/news/accenture-and-blue-yonder-help-companies-accelerate-supply-chain-transformation--in-the-cloud.htm
or with .page and it works fine and redirects properly. But when you test with tempnewsroom.accenture.com it doesn't because it has an older value. The redirects.json is cached and needs to be cleared.

I believe @raymond-h-dev is working on adding push invalidation for tempnewsroom domains to the config. Once that is in place, just re publish the redirects.xlsx and it will all work as intended.

I think that your CDN cache is impacting this testing and the 404 is cached somehow. Clear CDN cache and test it again.

this is in redirects.json for your reference:
```
{
      "Source": "/news/accenture-and-blue-yonder-help-companies-accelerate-supply-chain-transformation--in-the-cloud.htm",
      "Destination": "/news/2020/accenture-and-blue-yonder-help-companies-accelerate-supply-chain-transformation-in-the-cloud",
},
```        
```
{
      "Source": "/industries/consumer-goods--services.htm",
      "Destination": "/industries/consumer-goods-services",
}
```
