### ISSUE TITLE
313083 - [Newsroom] [UAT Testing] - Critical Pages - Tech Vision 2023 - Downloaded pdf appearance is not identical

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#355]
Description: Downloaded pdf appearance is not identical

Legacy: https://newsroom.accenture.com/news/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds.htm

Migrated: https://tempnewsroom.accenture.com/news/2023/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/6dce651f-9b3b-4595-a7e6-5e867441c311)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/3766e919-1de0-45f8-9e39-83556f171242)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/313083
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Is this really a high priority? The downloaded pdf won't look the same. the site, DOM, PDF library we are using are all different.

**Comment by amol-anand** [comment]
This is an issue with the original source content that got migrated with some BRs and NBSPs in the content.

This is what the page looked like after migration:

![Screenshot 2023-10-24 at 6 53 11 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/aa7e3d7e-27da-4eee-86bd-b7caeab8e61e)

I then edited the word doc and removed the unnecessary spaces in the content and then previewed and published it. Now it looks like this:
![Screenshot 2023-10-24 at 6 57 49 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/f9b0f301-7753-4bfe-8ed2-8a977b4ef40c)

Now when i click to download the pdf it looks fine. see attached.
[accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds.pdf](https://github.com/hlxsites/accenture-newsroom/files/13129648/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds.pdf)

This is not an issue with the pdf generation. but the source / migrated content. we did not alter the existing BRs and NBSPs in the original content because it should be the same. The original content html structure is not consistent to say the least. Not a bug in functionality. This is a content issue. If you do see this in specific pages, please fix the content in Word and preview/publish.
