### ISSUE TITLE
[Newsroom] [UAT Testing] - Critical Pages - Tech Vision 2023 - Incorrect article paragraph format

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#356]
Description: The text and paragraph is different from legacy page. Initial Text of the news is not aligned right ""Merging Physical and Digital Worlds"" and next two lines.

Legacy: https://newsroom.accenture.com/news/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds.htm

Migrated: https://tempnewsroom.accenture.com/news/2023/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/b7615738-3d8d-4c8f-8c98-3229ab8196c4)

Actual:
Image
Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/313016
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Source content has extra BRs and NBSP; between these lines which makes it look like two lines instead of one.

do you want us to remove BRs and NBSP; from the original content?

cc: @ravkiran

**Comment by veejayricana** [comment]
No, I think QA team wants to have an option that normal text can be aligned center.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e5bf1074-d963-4df4-8e06-cbd5d84c58b2)

cc: @jjjaspher @raymond-h-dev

**Comment by amol-anand** [comment]
@ravkiran I've updated the word doc to what they want. Can we adjust the CSS to respect multiple lines (except the last Paragraph) in abstract that is not H1 to be center aligned.

**Comment by ravkiran** [comment]
@veejayricana added support for centering the h6 in abstract in https://github.com/hlxsites/accenture-newsroom/pull/376
I've also updated https://tempnewsroom.accenture.com/news/2023/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds to use h6 for these two lines, so that the styles gets applied.

Example of how to make content h6
<img width="959" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/8380191e-afd9-4b6f-99fa-cd134ac9dd7a">
