### ISSUE TITLE
310834 - [Newsroom] [UAT Testing] - Critical Pages - Homepage - Different number of page pagination

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#363]
Description: Different number of page pagination to scroll thru

Legacy: https://newsroom.accenture.com/
Migrated: https://tempnewsroom.accenture.com/

Expected:- Has 528 pages to browse
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/419efba6-3fd7-4d9e-bbe0-01d203c5a870)

Actual: Has only 470 pages to browse
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1d834520-d9e7-4e95-b697-1e9113f8f6a5)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/310834
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Search is going to be different because we are looking for content in title, description, tags etc.. that is probably different from your existing site. Number of results / pages don't matter. whatever shows up in the first page of results matters.

I would not test search like this. Instead look for content and see if the right articles show up (better than what happens today)

cc: @raymond-h-dev

**Comment by amol-anand** [comment]
Currently i see 525 pages of article, not 470.

**Comment by amol-anand** [comment]
Seems to have been fixed by the reimport.

**Comment by ravkiran** [comment]
@veejayricana after re-import and cache cleared from ACC CDN, this issue seems to be fixed. Now, we're seeing 525 in franklin site.

<img width="1728" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/c14e5c3a-694c-490f-848d-071688039d6e">

The difference of 3 pages, can be ignored as some of the pages are leading to 404, some pages are not accessible, etc.
