### ISSUE TITLE
284942 - [Newsroom][Content Migration] Incomplete contents

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#390]
DESCRIPTION: Some contents in article list are not displayed in the migrated page.

MIGRATED PAGE:
https://tempnewsroom.accenture.de/de/subjects/diversity

LEGACY PAGE:
https://newsroom.accenture.de/de/subjects/diversity/

STEPS TO REPLICATE:
Open page in a browser
Compare contents under the following
Inclusion under Diversity in Zeiten von Social Distancing
Accenture-Studie zum Weltfrauentag: Kultur der Gleichstellung treibt Innovation am Arbeitsplatz 

ER:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/ad1be322-1596-4fc1-bf25-e9c378e05c85)

AR:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/578f83d6-adce-4ccd-9048-cbbd98f60f2b)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/284942
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
This can also be because of abstract that is missing

**Comment by ravkiran** [comment]
@veejayricana 
/de/news/2020/inclusion-und-diversity-in-zeiten-von-social-distancing - abstract is missing, when we manually add `---` this will be fixed.

For /de/news/2019/accenture-studie-zum-weltfrauentag-kultur-der-gleichstellung-treibt-innovation-am-arbeitsplatz - `Wien, 08. März 2019` is missing in the content of https://newsroom.accenture.de/de/news/accenture-studie-zum-weltfrauentag-kultur-der-gleichstellung-treibt-innovation-am-arbeitsplatz.htm so the abstract found is wrong, please fix this manually by adding `---` Please remember that even then we will not have the `Wien, 08. März 2019` as this content isn't there in the content of the document

**Comment by veejayricana** [comment]
Hi @ravkiran I already add 3 dashes in this document and publish but still the description that are been full is still not complete same in the legacy page. And also, upon checking the descript is on Strong font face but in the legacy it is not.
Migrated: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/a7c3c75d-9dd1-4d0b-b4bb-b3189880e174)
legacy: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7015e9fe-1551-468b-ade2-dfb7d4f67bec)

here is my test page for this: https://tempnewsroom.accenture.de/de/news/2020/inclusion-und-diversity-in-zeiten-von-social-distancing 

@amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana 
In the document, before `---` there's bold content, that's why its coming as strong in listing, I've updated the bold to normal in `Getting to Equal`, now its not showing as strong

For /de/news/2020/inclusion-und-diversity-in-zeiten-von-social-distancing - as there's no year in the abstract section (before `---`), it couldn't find the abstract paragraph, so its using the descirption. But the description field has the `strong`, so it was shown as bold. Now I've fixed that in the metadata, so no strong text. But this will not be same as the original as there's no year in the abstract, we can't obtain the abstract. Another way to fix this is to add an year in the starting of the `Pride Month` or to update what ever text you want in the meatdata table `description` field.
